apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "streamforge.fullname" . }}-dataset
  labels:
    {{- include "streamforge.labels" . | nindent 4 }}
data:
  dataset.yaml: |
{{ .Values.dataset.config | indent 4 }}
  raw.schema.json: |
{{ .Values.dataset.rawSchema | indent 4 }}
  normalized.schema.json: |
{{ .Values.dataset.normalizedSchema | indent 4 }}
