// Package sse collects JSON Server-Sent Events from one HTTP endpoint.
package sse

import (
	"bufio"
	"context"
	"crypto/sha256"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"mime"
	"net/http"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/Kale105/streamforge/internal/collector"
	"github.com/Kale105/streamforge/internal/event"
)

var (
	ErrInvalidConfig = errors.New("invalid SSE collector configuration")
	ErrRetryable     = errors.New("retryable SSE collection failure")
	ErrPermanent     = errors.New("permanent SSE collection failure")
	// Invalid wire data must not be retried indefinitely. The specific causes
	// remain matchable while also classifying as permanent for retry wrappers.
	ErrInvalidResponse = errors.Join(errors.New("invalid SSE response"), ErrPermanent)
	ErrMessageTooLarge = errors.Join(errors.New("SSE message exceeds maximum size"), ErrPermanent)
)

// defaultMaxRetryDelay limits server-advertised reconnect delays when a caller
// does not select a smaller operational limit.
const defaultMaxRetryDelay = 24 * time.Hour

// Cursor is the durable position of an SSE collector. Sequence is generated by
// this host, rather than inferred from the provider's opaque (and potentially
// repeated) SSE ID.
type Cursor struct {
	Sequence    uint64
	LastEventID string
}

// CommitFunc persists the position only after Emit has durably accepted an
// event. eventID is supplied for an audit/checkpoint implementation.
type CommitFunc func(ctx context.Context, sequence uint64, lastEventID, eventID string) error

// Config bounds the deliberately small supported SSE subset: UTF-8 lines with
// data, id, event and retry fields; one event is dispatched by a blank line.
// Each event's concatenated data must be a single JSON value. Collect makes one
// connection only; callers can wrap it in collector/retry for bounded reconnects.
type Config struct {
	URL             string
	Source          string
	Type            string
	MaxMessageBytes int
	MaxLineBytes    int
	RequestTimeout  time.Duration
	// InitialCursor must be the last successfully committed position. It is
	// used for the very first Last-Event-ID header as well as event sequencing.
	InitialCursor Cursor
	// RequireEventID is appropriate for provider mode: a data event without a
	// non-empty SSE id is rejected instead of becoming impossible to resume.
	RequireEventID bool
	// Commit is called after Emit succeeds and before the in-memory cursor is
	// advanced. Nil retains the legacy in-memory-only behavior.
	Commit CommitFunc
	// MaxRetryDelay caps a server retry field. Zero selects the safe default.
	MaxRetryDelay time.Duration
	// RetryHint receives each accepted, capped server retry delay. It lets the
	// owning reconnect policy opt in to SSE guidance without coupling this
	// collector to a particular retry package.
	RetryHint func(time.Duration)
}

type Collector struct {
	config    Config
	client    *http.Client
	mu        sync.RWMutex
	cursor    Cursor
	retry     time.Duration
	collectMu sync.Mutex
}

func New(config Config, client *http.Client) (*Collector, error) {
	if strings.TrimSpace(config.URL) == "" || strings.TrimSpace(config.Source) == "" || strings.TrimSpace(config.Type) == "" || config.MaxMessageBytes <= 0 || config.MaxMessageBytes > event.MaxDataBytes || config.MaxLineBytes <= 0 || config.MaxLineBytes > config.MaxMessageBytes || config.RequestTimeout <= 0 || client == nil {
		return nil, fmt.Errorf("%w: URL, source, type, client, positive bounded line/message sizes, and timeout are required", ErrInvalidConfig)
	}
	req, err := http.NewRequest(http.MethodGet, config.URL, nil)
	if err != nil || (req.URL.Scheme != "http" && req.URL.Scheme != "https") {
		return nil, fmt.Errorf("%w: URL must use HTTP or HTTPS", ErrInvalidConfig)
	}
	if config.MaxRetryDelay < 0 {
		return nil, fmt.Errorf("%w: max retry delay cannot be negative", ErrInvalidConfig)
	}
	if config.MaxRetryDelay == 0 {
		config.MaxRetryDelay = defaultMaxRetryDelay
	}
	if strings.ContainsRune(config.InitialCursor.LastEventID, '\x00') || len(config.InitialCursor.LastEventID) > event.MaxIDBytes {
		return nil, fmt.Errorf("%w: initial last event ID exceeds maximum size", ErrInvalidConfig)
	}
	return &Collector{config: config, client: client, cursor: config.InitialCursor}, nil
}

// LastEventID returns the resume token retained by this collector instance.
func (c *Collector) LastEventID() string { return c.Cursor().LastEventID }

// Cursor returns a snapshot of the last successfully committed position.
func (c *Collector) Cursor() Cursor { c.mu.RLock(); defer c.mu.RUnlock(); return c.cursor }

// RetryDelay is the last valid retry field advertised by the server (or zero).
func (c *Collector) RetryDelay() time.Duration { c.mu.RLock(); defer c.mu.RUnlock(); return c.retry }

func (c *Collector) Collect(ctx context.Context, emit collector.EmitFunc) error {
	if emit == nil {
		return fmt.Errorf("%w: emit function is required", ErrInvalidConfig)
	}
	// A cursor describes one ordered stream. Concurrent Collect calls would
	// otherwise allocate the same host sequence before either commits it.
	c.collectMu.Lock()
	defer c.collectMu.Unlock()
	// The deadline bounds a stalled connection and a stalled stream. A caller
	// wanting a long-lived stream should choose an appropriately long duration.
	reqCtx, cancel := context.WithTimeout(ctx, c.config.RequestTimeout)
	defer cancel()
	req, err := http.NewRequestWithContext(reqCtx, http.MethodGet, c.config.URL, nil)
	if err != nil {
		return fmt.Errorf("%w: request: %v", ErrPermanent, err)
	}
	req.Header.Set("Accept", "text/event-stream")
	if id := c.LastEventID(); id != "" {
		req.Header.Set("Last-Event-ID", id)
	}
	resp, err := c.client.Do(req)
	if err != nil {
		if ctx.Err() != nil {
			return ctx.Err()
		}
		return fmt.Errorf("%w: request: %v", ErrRetryable, err)
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		if resp.StatusCode == http.StatusTooManyRequests || resp.StatusCode >= 500 {
			return fmt.Errorf("%w: unexpected status %d", ErrRetryable, resp.StatusCode)
		}
		return fmt.Errorf("%w: unexpected status %d", ErrPermanent, resp.StatusCode)
	}
	mediaType, _, parseErr := mime.ParseMediaType(resp.Header.Get("Content-Type"))
	if parseErr != nil || mediaType != "text/event-stream" {
		return fmt.Errorf("%w: content type must be text/event-stream", ErrInvalidResponse)
	}
	if err := c.parse(reqCtx, resp.Body, emit); err != nil {
		if ctx.Err() != nil {
			return ctx.Err()
		}
		return err
	}
	return fmt.Errorf("%w: stream ended", ErrRetryable)
}

func (c *Collector) parse(ctx context.Context, body io.Reader, emit collector.EmitFunc) error {
	s := bufio.NewScanner(body)
	s.Buffer(make([]byte, 1024), c.config.MaxLineBytes)
	var data []string
	var id, eventType string
	hasID := false
	dispatch := func() error {
		if len(data) == 0 {
			return nil
		}
		raw := []byte(strings.Join(data, "\n"))
		if len(raw) > c.config.MaxMessageBytes {
			return ErrMessageTooLarge
		}
		if !json.Valid(raw) {
			return fmt.Errorf("%w: event data is not JSON", ErrInvalidResponse)
		}
		typ := c.config.Type
		if eventType != "" {
			typ = eventType
		}
		if c.config.RequireEventID && (!hasID || id == "") {
			return fmt.Errorf("%w: event id is required", ErrInvalidResponse)
		}
		prior := c.Cursor()
		next := Cursor{Sequence: prior.Sequence + 1, LastEventID: prior.LastEventID}
		if hasID {
			next.LastEventID = id
		}
		// SSE IDs are opaque resume tokens and may repeat. The host sequence is
		// durable and makes distinct occurrences distinct without making a retry
		// after a failed checkpoint generate a new event identity.
		eid := stableID(c.config.Source, typ, next.Sequence, id, raw)
		e := event.Event{SpecVersion: event.SpecVersion, ID: eid, Source: c.config.Source, Type: typ, Time: time.Now().UTC(), Data: append(json.RawMessage(nil), raw...)}
		if err := e.Validate(); err != nil {
			return fmt.Errorf("%w: constructed event: %v", ErrInvalidResponse, err)
		}
		if err := emit(ctx, e); err != nil {
			return err
		}
		if c.config.Commit != nil {
			if err := c.config.Commit(ctx, next.Sequence, next.LastEventID, e.ID); err != nil {
				return fmt.Errorf("%w: checkpoint: %w", ErrRetryable, err)
			}
		}
		// This assignment deliberately follows Commit. A process failure in the
		// preceding gap restarts at prior and duplicates; it cannot skip data.
		c.mu.Lock()
		c.cursor = next
		c.mu.Unlock()
		data = nil
		eventType = ""
		hasID = false
		return nil
	}
	for s.Scan() {
		line := s.Text()
		if line == "" {
			if err := dispatch(); err != nil {
				return err
			}
			continue
		}
		if strings.HasPrefix(line, ":") {
			continue
		}
		field, value, ok := strings.Cut(line, ":")
		if !ok {
			value = ""
		}
		value = strings.TrimPrefix(value, " ")
		switch field {
		case "data":
			if total(data)+len(value)+len(data) > c.config.MaxMessageBytes {
				return ErrMessageTooLarge
			}
			data = append(data, value)
		case "id":
			if strings.ContainsRune(value, '\x00') || len(value) > event.MaxIDBytes {
				return fmt.Errorf("%w: invalid event id", ErrInvalidResponse)
			}
			id = value
			hasID = true
		case "event":
			if len(value) > event.MaxTypeBytes {
				return fmt.Errorf("%w: event type too long", ErrInvalidResponse)
			}
			eventType = value
		case "retry":
			if n, err := strconv.ParseInt(value, 10, 64); err == nil && n >= 0 {
				delay := cappedRetryDelay(n, c.config.MaxRetryDelay)
				c.mu.Lock()
				c.retry = delay
				c.mu.Unlock()
				if c.config.RetryHint != nil {
					c.config.RetryHint(delay)
				}
			}
		}
	}
	if err := s.Err(); err != nil {
		if strings.Contains(err.Error(), "token too long") {
			return ErrMessageTooLarge
		}
		return fmt.Errorf("%w: read stream: %v", ErrRetryable, err)
	}
	return dispatch()
}
func total(parts []string) int {
	n := 0
	for _, p := range parts {
		n += len(p)
	}
	return n
}
func cappedRetryDelay(milliseconds int64, maximum time.Duration) time.Duration {
	if milliseconds > int64(maximum/time.Millisecond) {
		return maximum
	}
	return time.Duration(milliseconds) * time.Millisecond
}

func stableID(source, typ string, sequence uint64, sseID string, data []byte) string {
	sum := sha256.Sum256([]byte(source + "\n" + typ + "\n" + strconv.FormatUint(sequence, 10) + "\n" + sseID + "\n"))
	h := sha256.New()
	_, _ = h.Write(sum[:])
	_, _ = h.Write(data)
	return fmt.Sprintf("sse-%x", h.Sum(nil))
}

var _ collector.Collector = (*Collector)(nil)
